QBS: [Daniel Jones,
      Tua Tagovailoa,
      Lamar Jackson,
      Josh Allen,
      Joe Burrow,
      Baker Mayfield,
      Teddy Bridgewater,
      Tyrod Taylor,
      Carson Wentz,
      Trevor Lawrence,
      Patrick Mahomes,
      Derek Carr,
      Justin Herbert,
      Mac Jones,
      Ben Roethlisberger,
      Ryan Tannehill,
      Matt Ryan,
      Kyler Murray,
      Sam Darnold,
      Andy Dalton,
      Dak Prescott,
      Jared Goff,
      Aaron Rodgers,
      Matt Stafford,
      Kirk Cousins,
      Jameis Winston,
      Jalen Hurts,
      Jimmy Garoppolo,
      Russell Wilson,
      Tom Brady,
      Taylor Heinicke]

Season: '2021REG'
Week: '1'
Year: '2021'
